version: '3'
services:
  prank:
    image: larshaalck/paper-rank:latest
    restart: unless-stopped
    volumes:
      - ./db:/opt/prank/db
      - ./Rocket.toml:/opt/prank/Rocket.toml
    env_file:
    - .env
    ports:
      - "8000:8000"
