version: '3'
services:
  voters:
    image: larshaalck/voters:latest
    restart: unless-stopped
    volumes:
      - ./db:/opt/voters/db
      - ./Rocket.toml:/opt/voters/Rocket.toml
    env_file:
    - .env
    ports:
      - "8000:8000"
